server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test?useSSL=false
#    username: root
#    password: kang0929
#    driver-class-name: com.mysql.jdbc.Driver
#    initialize: false
    url: jdbc:sqlite:blog-test.db
  jpa:
    show-sql: false